name: CI
on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    env:
      VFLAGS: -cc gcc -cg
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: "8.x"
      
      - name: Installing v
        run: |
          git clone https://github.com/vlang/v.git
          cd v/
          make CC=gcc
          sudo ./v symlink
          
      - name: Compile VSymbols
        run: v ./src/vsymbols -o ./bin/vsymbols
          
      - name: Install vsce
        run: npm install --global vsce
        
      - name: Install dependencies
        run: npm install

      - name: Webpack
        run: npm run webpack

      - name: Package
        run: npm run compile-vsymbols && vsce package  && npm run restore-json


  build-windows-gcc:
    runs-on: windows-2019
    env:
      VFLAGS: -cc gcc -cg
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: "8.x"
      
      - name: Installing V
        run: |
          git clone https://github.com/vlang/v.git d:\v
          cd d:\v
          .\make.bat -gcc
          .\v symlink
          echo "::add-path::d:\v"

      - name: Verify v is in path
        run: |
          pwd
          v version

      - name: Compile VSymbols
        run: v .\src\vsymbols -o .\bin\vsymbols
          
      - name: Install vsce
        run: npm install --global vsce
        
      - name: Install dependencies
        run: npm install
                
      - name: Webpack
        run: npm run webpack
        
      - name: Package
        run: npm run compile-vsymbols && vsce package  && npm run restore-json
